import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import AnimationProvider from "@/components/provider/AnimationProvider";
import FloatingChatFAB from "@/components/shared/FloatingChartFAB";
// import { NavigationMenuDemo } from "@/components/shared/NavigationMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        <AnimationProvider>
          <main className="mt-24 ">
            {children}
          </main>
        </AnimationProvider>
        <Footer />
        <FloatingChatFAB />
      </body>
    </html>
  );
}
